### PR TITLE
create a README

### PR DESCRIPTION
**Pull request by sojeri**
add the contents of the repo description to said README

NOTE: I thoughtlessly used `contributing.md` as the first commit to this repo, so please [review that file on master branch](https://github.com/trussworks/.github/blob/master/CONTRIBUTING.md) and leave comments on this PR with any changes you recommend.

### CODE REVIEW

**Comment by brainsik** [comment]
I like the concept! Only change I'd like to see is dropping the final paragraph. I'm not seeing any value in pointing folks [this section in the engineering playbook](https://github.com/trussworks/Engineering-Playbook/tree/master/infra/tf).

**Comment by sojeri** [comment]
> I like the concept! Only change I'd like to see is dropping the final paragraph. I'm not seeing any value in pointing folks [this section in the engineering playbook](https://github.com/trussworks/Engineering-Playbook/tree/master/infra/tf).

I know it *seems* empty. I have a [PR out that should fill in some details there](https://github.com/trussworks/Engineering-Playbook/pull/18), and I wonder if this changes your thoughts on removing the last paragraph, @brainsik.

**Comment by gidjin** [comment]
This looks fine to me, assuming brainsik's comment is satisfied.

**Comment by gidjin** [comment]
After looking at the contributing.md file I'm wondering if one week is too short of a response time. Perhaps if it's been 2 - 4 weeks would be better since the terraform modules are not necessarily our top priority at any given time as a consultancy.

**Comment by rpdelaney** [comment]
@gidjin since that's already in the repo maybe this should be discussed in a different issue?

**Comment by sojeri** [comment]
> @gidjin since that's already in the repo maybe this should be discussed in a different issue?

@rpdelaney -- per this PR's description: "NOTE: I thoughtlessly used contributing.md as the first commit to this repo, so please review that file on master branch and leave comments on this PR with any changes you recommend."

**Review by gidjin — APPROVED** [review]
LGTM

**Pull request merged**
